version: '3'
services:
  sarna:
    build: .
    volumes:
      - vol_sarna_upload:/sarna/uploaded_data
      - vol_sarna_config:/sarna/config
    environment:
      FLASK_ENV: 'production'
      SQLALCHEMY_DATABASE_URI: 'postgres://user:password@psql/sarna'
      SECRET_KEY: 'Insecure Secret Change Me!!'
    depends_on:
      - psql
    ports:
      - "5000:5000"
  psql:
    image: postgres
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'sarna'
    volumes:
      - vol_sarna_db:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
volumes:
  vol_sarna_db:
  vol_sarna_upload:
  vol_sarna_config: