version: '3'
services:
  sarna:
    build: .
    volumes:
      - ./volumes/uploaded_data:/sarna/uploaded_data
      - ./volumes/config:/sarna/config
    environment:
      FLASK_ENV: 'development'
      SQLALCHEMY_DATABASE_URI: 'postgres://sarna:InsecurePasswordChangeMe@psql/sarna'
      SECRET_KEY: 'Insecure Secret Change Me!!'
    depends_on:
      - psql
    ports:
      - "5000:5000"
  psql:
    image: postgres
    environment:
      POSTGRES_USER: 'sarna'
      POSTGRES_PASSWORD: 'InsecurePasswordChangeMe'
      POSTGRES_DB: 'sarna'
    volumes:
      - ./volumes/database:/var/lib/postgresql/data

